version: '3'

services:
  tgbot:
    container_name: tgbot
    volumes:
      - .:/tgbot
    env_file:
      - tgbot/.env
    environment:
      BOT_HOME: tgbot
      TZ: Asia/Shanghai

    build: .
    stop_signal: SIGINT
      
  tgbot2:
    container_name: tgbot2
    volumes:
      - .:/tgbot
    env_file:
      - tgbot2/.env
    environment:
      BOT_HOME: tgbot2
      TZ: Asia/Shanghai
    
    build: .
    stop_signal: SIGINT
    depends_on:
      - tgbot
